version: "3.8"
services:
  api:
    build: ./backend/api
    ports:
      - 3001:3001
    depends_on:
      - "postgres"
  
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    volumes:
      - ./backend/db/postgres-data:/var/lib/postgresql/data
      - ./backend/db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./backend/db/.env
    ports:
      - 5432:5432

  frontend:
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 8080:3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  
 

